// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("BigQueryProvider.Runtime")>]
[<assembly: AssemblyProductAttribute("BigQueryProvider")>]
[<assembly: AssemblyDescriptionAttribute("F# type provider for BigQuery")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "BigQueryProvider.Runtime"
    let [<Literal>] AssemblyProduct = "BigQueryProvider"
    let [<Literal>] AssemblyDescription = "F# type provider for BigQuery"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
